// Simple mapping from model labels / user inputs -> canonical ingredient names
const CANONICAL = [
  "tomato",
  "onion",
  "garlic",
  "potato",
  "carrot",
  "bell pepper",
  "chicken",
  "beef",
  "egg",
  "milk",
  "butter",
  "olive oil",
  "flour",
  "rice",
  "pasta",
  "broccoli",
  "spinach",
  "mushroom",
  "cheese",
  "yogurt",
  "lemon",
  "lime",
  "apple",
  "banana",
  "cucumber",
  "zucchini",
  "salt",
  "pepper",
  "cumin",
  "coriander",
  "paprika",
  "ginger",
  "cilantro",
  "parsley",
  "chickpeas",
  "lentils",
  "beans",
  "tofu",
  "soy sauce",
  "vinegar",
  "honey",
  "sugar",
  "paneer",
  "cream",
  "mango",
  "strawberry",
  "blueberry",
  "raspberry",
  "orange",
  "grape",
  "pineapple",
  "watermelon",
  "avocado",
  "kale",
  "lettuce",
  "cabbage",
  "cauliflower",
  "peas",
  "corn",
  "eggplant",
  "quinoa",
  "oats",
  "almond",
  "cashew",
  "walnut",
  "peanut",
  "coconut",
  "basil",
  "oregano",
  "thyme",
  "rosemary",
  "mint",
];

const MAP = {
  // common synonyms and mobilenet labels
  "granny smith": "apple",
  "bell pepper": "bell pepper",
  "sweet pepper": "bell pepper",
  capsicum: "bell pepper",
  scallion: "onion",
  shallot: "onion",
  "green onion": "onion",
  "spring onion": "onion",
  aubergine: "eggplant",
  eggplant: "eggplant",
  courgette: "zucchini",
  coriander: "cilantro",
  "ground beef": "beef",
  beefsteak: "beef",
  poultry: "chicken",
  "chicken breast": "chicken",
  "chicken thigh": "chicken",
  "chicken drumstick": "chicken",
  yolk: "egg",
  dairy: "milk",
  yogurt: "yogurt",
  curd: "yogurt",
  dahi: "yogurt",
  maize: "corn",
  corn: "corn",
  chilli: "pepper",
  chili: "pepper",
  "chilli pepper": "pepper",
  ketchup: "tomato",
  "tomato sauce": "tomato",
  "tomato ketchup": "tomato",
  "bell pepper, sweet pepper": "bell pepper",
  // Paneer synonyms
  paneer: "paneer",
  "cottage cheese": "paneer",
  "indian cheese": "paneer",
  // Fruit synonyms
  mango: "mango",
  "alphonso mango": "mango",
  banana: "banana",
  plantain: "banana",
  strawberry: "strawberry",
  strawberries: "strawberry",
  blueberry: "blueberry",
  blueberries: "blueberry",
  raspberry: "raspberry",
  raspberries: "raspberry",
  orange: "orange",
  mandarin: "orange",
  tangerine: "orange",
  grape: "grape",
  grapes: "grape",
  pineapple: "pineapple",
  watermelon: "watermelon",
  avocado: "avocado",
  // Vegetable synonyms
  kale: "kale",
  lettuce: "lettuce",
  "iceberg lettuce": "lettuce",
  "romaine lettuce": "lettuce",
  cabbage: "cabbage",
  cauliflower: "cauliflower",
  peas: "peas",
  "green peas": "peas",
  "sweet corn": "corn",
  brinjal: "eggplant",
  // Grain and seeds
  quinoa: "quinoa",
  oats: "oats",
  oatmeal: "oats",
  // Nuts
  almond: "almond",
  almonds: "almond",
  cashew: "cashew",
  cashews: "cashew",
  "cashew nuts": "cashew",
  walnut: "walnut",
  walnuts: "walnut",
  peanut: "peanut",
  peanuts: "peanut",
  "peanut butter": "peanut",
  coconut: "coconut",
  // Herbs
  basil: "basil",
  "holy basil": "basil",
  oregano: "oregano",
  thyme: "thyme",
  rosemary: "rosemary",
  mint: "mint",
  peppermint: "mint",
  // Dairy
  cream: "cream",
  "heavy cream": "cream",
  "whipping cream": "cream",
  milk: "milk",
  "whole milk": "milk",
  "skim milk": "milk",
};

export function toCanonical(label) {
  if (!label) return null;
  const low = String(label).toLowerCase();
  if (MAP[low]) return MAP[low];
  // simple contains matching
  for (const c of CANONICAL) {
    if (low.includes(c)) return c;
  }
  // try splitting on commas and choosing first token
  const base = low.split(",")[0].trim();
  if (MAP[base]) return MAP[base];
  return null;
}
